### ISSUE TITLE
Jade Addons does not hide SecretRoomsMod blocks properly.

### ISSUE THREAD

**Issue by Jackbusters** [Snownee/JadeAddons#13]
### Mod loader

Forge

### Minecraft version

1.19.2

### Mod version

3.1.0

### Modloader version

43.1.58

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://pastebin.com/ARcP6VW0

### Issue description

Jade Addons does not hide SecretRoomsMod blocks properly.
Secret Rooms Mod Version: 1.2.0
Forge Version: 43.1.58
Jade Version: 8.6.0
![2022-11-28_18 21 05](https://user-images.githubusercontent.com/77648717/204408390-d27aa7c9-dc12-49c8-8a7d-ae5cc4a2061f.png)
![2022-11-28_18 21 16](https://user-images.githubusercontent.com/77648717/204408399-559fdf1b-3f19-40a8-a47c-999a6c1ebd00.png)

**Comment by Snownee** [comment]
test it in survival mode

**Comment by Snownee** [comment]
SecretRoomsMod support for 1.19.2 is not added yet
