### ISSUE TITLE
[Create 1.18.2 Bug] Copycat blocks in contraptions show nothing as a block preview

### ISSUE THREAD

**Issue by Ch1216** [Snownee/JadeAddons#19]
### Mod loader

Forge

### Minecraft version

1.18.2

### Mod version

5.2.3

### Modloader version

36.2.4

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://pastebin.com/A3H1GS9m

### Issue description

Copycat blocks in contraption do not show a block preview (Note: when pressing shift they show a block preview of the copycat block, not a block preview of what the block actually is ex: grass block for the pic)
![xwoiaschufvcnas](https://github.com/Snownee/JadeAddons/assets/68875386/eeabd60e-e1e8-4b1f-bb18-77b6368ff850)

**Comment by Snownee** [comment]
fixed in 1.20. 1.18.2 is no longer maintained
