### ISSUE TITLE
5.0.0 Labeled as 1.19.2 on Modrinth

### ISSUE THREAD

**Issue by EpicGazel** [Snownee/JadeAddons#20]
### Mod loader

Forge

### Minecraft version

1.19.2

### Mod version

5.0.0

### Modloader version

Forge: 43.2.10

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### Issue description

On Modrinth, JadeAddons 5.0.0 is improperly labeled as 1.19.2 when it is presumably meant to be 1.20/1.20.1 like on CurseForge. Using 5.0.0 in 1.19.2 causes a crash due to mismatched javafml versions.

**Comment by Snownee** [comment]
Thanks
