### ISSUE TITLE
Productive Bees attributes toggle ineffective

### ISSUE THREAD

**Issue by OoTMaestro** [Snownee/JadeAddons#26]
### Mod loader

Forge

### Minecraft version

1.20.1

### Mod version

5.2.0

### Modloader version

47.1.3

### Modpack info

ATM 9

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

Productive Bees Attributes toggle under Config > Plugin Settings > Productive Bees > Attributes does not have an effect. Attributes are not displayed when toggle is either on or off.

**Comment by OoTMaestro** [comment]
There's a very good chance I put this in the wrong spot, not sure if the JadeAddons is where the ability to interface with other mods comes from, apologies if I made this in error.

**Comment by Snownee** [comment]
Please report to Productive Bees devs. Jade Addons does not contain Productive Bees integration
