### ISSUE TITLE
LootR Refresh Timer Bug

### ISSUE THREAD

**Issue by LegitGamer1017** [Snownee/JadeAddons#27]
### Mod loader

Forge

### Minecraft version

1.201

### Mod version

5.2.0

### Modloader version

NeoForge 47.1.79

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://gist.github.com/LegitGamer1017/c8c5ad1be778e44d8ea6d001e2abd163

### Issue description

![image](https://github.com/Snownee/JadeAddons/assets/46847496/29512009-c5fb-4df4-805d-0eebc28b10c0)

I only had LootR, Jade, and Jade Plugins enabled.

**Comment by Snownee** [comment]
update Jade
