### ISSUE TITLE
The armor support descriptions do not load, and with the create mod

### ISSUE THREAD

**Issue by 0Trinster0** [Snownee/JadeAddons#28]
### Mod loader

Forge

### Minecraft version

1.19.2

### Mod version

8.9.1

### Modloader version

forge 43.3.0

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

![2023-11-10_10 16 59](https://github.com/Snownee/JadeAddons/assets/150207340/c8538c60-5ce4-400a-9f6b-b373b5896a01)
![2023-11-10_10 16 54](https://github.com/Snownee/JadeAddons/assets/150207340/395bf13b-cfb4-48a5-8a15-f6241cf644dd)

The latest version of jade addons does not load correctly either.

**Comment by Snownee** [comment]
I can't reproduce it. Can you find the JadeErrorOutput.txt in the logs folder?
