### ISSUE TITLE
OpenBlocks Elevator Support

### ISSUE THREAD

**Issue by Lukebb04** [Snownee/JadeAddons#3]
### Mod loader

Forge

### Minecraft version

1.18.2

### Mod version

2.0.0

### Modloader version

Forge: 40.1.54

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

Add support for camouflage elevator blocks from [OpenBlocks Elevator](https://www.curseforge.com/minecraft/mc-mods/openblocks-elevator)

**Comment by Snownee** [comment]
currently no plan
