### ISSUE TITLE
[Suggestion] Add info about block speed from Block Runner & Happy Trails

### ISSUE THREAD

**Issue by DanteTooMayCry** [Snownee/JadeAddons#31]
### Mod loader

Forge

### Minecraft version

All

### Mod version

All

### Modloader version

All

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

Both mods allow you to change the movement speed on different blocks. The first one adds such information in the recipe book, but it would be nice if this information could appear after hovering over a placed block.

![305944142-43921408-6b72-4787-ac61-017fe4991d57](https://github.com/Snownee/JadeAddons/assets/108282775/dc8c211d-3422-4018-bd58-41ac9d8707b5)

**Comment by Snownee** [comment]
Thanks for the suggestion. We have no plans for this at this time.
