### ISSUE TITLE
Promote this mod in minbbs

### ISSUE THREAD

**Issue by qim147** [Snownee/JadeAddons#36]
### Mod loader

Fabric

### Minecraft version

*

### Mod version

*

### Modloader version

*

### [IMPORTANT] If bug:

- [ ] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### Issue description

MineBBS is a Minecraft forum from China, and I would like to post this mod on this forum so that more Chinese players can know about this mod.(Because this passage is translated, it may not be accurate, so please bear with me
)

**Comment by qim147** [comment]
I don't distribute mod files

**Comment by Snownee** [comment]
不传播文件则不需要获得作者许可。请知晓这一原则，不要打扰其他作者们。

顺带一提：考虑使用好一点的翻译器😛

**Comment by qim147** [comment]
> 不传播文件则不需要获得作者许可。请知晓这一原则，不要打扰其他作者们。
> 
> 顺带一提：考虑使用好一点的翻译器😛
thanks
