### ISSUE TITLE
Re-Add Tinkers'Compat to 1.19.2 version

### ISSUE THREAD

**Issue by ffuentesm** [Snownee/JadeAddons#37]
### Mod loader

Forge

### Minecraft version

1.19.2

### Mod version

3.6.0

### Modloader version

43.3.0

### [IMPORTANT] If bug:

- [ ] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### Issue description

Tinker's updated to 1.19.2, but the Jade Add-on no longer displays the information of cooling liquid, and other features from 1.18.x version.

**Comment by Snownee** [comment]
Sorry, I no longer maintain 1.19.2. I will consider adding it if Tinkers is on 1.20.1 in the future
