### ISSUE TITLE
Create .5 train server crash

### ISSUE THREAD

**Issue by TheCebulaShark** [Snownee/JadeAddons#5]
### Mod loader

Forge

### Minecraft version

1.18.2

### Mod version

2.0.0

### Modloader version

Forge 40.1.54

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://pastebin.com/jwV0TUuj

### Issue description

Server sesion closed after lookig at train costraption from the newest 0.5 create mod version

**Comment by SeanChengN** [comment]
Same

**Comment by tukib** [comment]
I think it is just this line that needs to be changed

https://github.com/Snownee/JadeAddons/blob/1.18.2-forge/src/main/java/snownee/jade/addon/create/ContraptionProvider.java#L36

to `InventoryProvider.putInvData(data, contraption.getSharedInventory(), size, 0);`
