### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by CapivaraTupiniquim** [Snownee/JadeAddons#7]
### Mod loader

Forge

### Minecraft version

1.18.2

### Mod version

0

### Modloader version

0

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

**Comment by Ch1216** [comment]
what?

**Comment by CapivaraTupiniquim** [comment]
It would be interesting to contain the changes made in each new release.

**Comment by Ch1216** [comment]
they added one to the [latest one](https://www.curseforge.com/minecraft/mc-mods/jade-addons/files/3886082) i guess issue resolved
