### ISSUE TITLE
Create contraption only shows the inventory of 1 container

### ISSUE THREAD

**Issue by Ch1216** [Snownee/JadeAddons#8]
### Mod loader

Forge

### Minecraft version

1.18.2

### Mod version

2.4.0

### Modloader version

Forge 40.1.0

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://pastebin.com/wEfM0bR9

### Issue description

When looking at a contraption it will choose a block to focus on and not any others even if the focused blocks has no items and others do

**Comment by Snownee** [comment]
I can't understand what you mean

**Comment by Ch1216** [comment]
Example, there are 2 barrels on a contraption one on top of each other, when the contraption is assembled it will only show the contents of the top barrel even if it has nothing inside it or if your looking at a another barrel

A suggestion on how to show the items is to show the one with the most items or only show the contents of a container your looking at

**Comment by Ch1216** [comment]
I did not know that if you shifted you could see the whole contraption inventory  instead of viewing the container farthest from the contraption source (I think that's how it works)

I do still feel you should go with my suggestions for unshifting behaviour and explain it somewhere

or if you cant but can add more support for create try my [other suggestion I edited](https://github.com/Snownee/JadeAddons/issues/2#issuecomment-1069080580)
